Repository StanfordSpezi/SpeziTemplateApplication, pull requests merged in 2025-01, with the labels that each got.

#93 Updates setup tutorial
  TemplateApplication.xcodeproj/project.pbxproj
  TemplateApplication.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TemplateApplication/Resources/Localizable.xcstrings
  TemplateApplication/Supporting Files/TemplateApplication.docc/Resources/Setup/Xcode.png
  TemplateApplication/Supporting Files/TemplateApplication.docc/Resources/Setup/Xcode~dark.png
  TemplateApplication/Supporting Files/TemplateApplication.docc/Setup.md
Labels: documentation

#94 Fix Main Branch Documentation Deployment Not Working
  .github/workflows/documentation-deployment.yml
Labels: documentation

#96 Fix CodeQL Reporting
  .github/workflows/documentation-deployment.yml
  .github/workflows/static-analysis.yml
  README.md
  TemplateApplicationUITests/ContributionsTest.swift
  TemplateApplicationUITests/SchedulerTests.swift
Labels: bug

#97 Fix Warnings
  .periphery.yml
  TemplateApplication.xcodeproj/project.pbxproj
  TemplateApplication/Account/AccountSetupHeader.swift
  TemplateApplication/TemplateApplicationStandard.swift
Labels: enhancement
